### ISSUE TITLE
0x60F (TPMS)

### ISSUE THREAD

**Issue by Lanchon** [prototux/PSA-RE#3]
hi,

given the data in [this table](https://git.prototux.net/reverse-engineering/psa/canbus/-/issues/140), it looks like the format of 0x60F as a bit string is as follows:

00 PFL(Pressure Front Left) PFR PRL PRR 111111 00 DFL(Deflation Front Left) DFR DRL DRR 111111

Pxx and Dxx are 6-bit integer values expressed in decibar. note that [35 PSI ≃ 24.13165 dbar](https://duckduckgo.com/?q=35+PSI+in+dbar&ia=answer).

Pxx is the current pressure (possibly corrected for wheel temperature), and Dxx is the current difference from some maximum value observed earlier.

thanks.

**Comment by prototux** [comment]
Thanks! i've added both 0x50F and 0x60F, which AFAIK are the only DSG frames (on the IS bus, as the DSG is on the IS bus). The delta seems to be the delta between now and the last data the sensor sent (to calculate the rate of deflation if any, and check if it's just the wheel being deflated or if the tyres are punctured).

**Comment by Lanchon** [comment]
thanks!

>  The delta seems to be the delta between now and the last data the sensor sent

but clearly not. according to the table linked above, data being sent does not reset the "max" value form which deflation values are computed. during the whole time that table was constructed, all 4 max values stayed constant even though data was being reported. (also deltas would require encoding of negative numbers.)

most likely, measured tire pressure is first adjusted for temperature (either to a idealized ambient temperature -say, 20 Celsius-, or less likely to the current outside temperature) and maybe adjusted for atmospheric pressure too (but that is less likely because it requires knowledge of elasticity properties of the tires). then inflation is detected and the max inflation value is recorded. after that, deflation will be measured against that stored unchanging value, so that slow rate deflation still triggers an error eventually.
